name: open_llm_vtuber
description: A state-of-the-art Flutter VTuber application with Live2D integration and AI backend communication.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Animation
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  glassmorphism: ^3.0.0
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # WebSocket and HTTP
  web_socket_channel: ^2.4.5
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.5
  
  # Audio
  audioplayers: ^6.0.0
  flutter_sound: ^9.2.13
  record: ^5.1.2
  permission_handler: ^11.3.1
  
  # Live2D and Animation
  flutter_gl: ^0.0.4
  flutter_cube: ^0.1.1
  
  # Storage and Preferences
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # Utilities
  path_provider: ^2.1.3
  uuid: ^4.4.0
  rxdart: ^0.27.7
  json_annotation: ^4.9.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
    - assets/audio/
    - assets/fonts/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700